### PR TITLE
Use less replicas on upgrade test

### PR DESCRIPTION
**Pull request by wallyqs**
It has been failing a couple of times with timeouts.
Signed-off-by: Waldemar Quevedo <wally@synadia.com>

### CODE REVIEW

**Comment by pires** [comment]
Well, maybe we could investigate why it is timing out?

**Comment by wallyqs** [comment]
@pires anyway to bubble those errors from the skaffold run?

**Comment by wallyqs** [comment]
It is usually the last test and failing on waiting for the cluster to come up, and since not failing locally guess it might be due to temp lack of resources on the Travis minikube.  We may have some instances being tore down async in between tests that could cause that which could be another thing to look at.

**Comment by wallyqs** [comment]
Locally can make it fail when the test suite takes longer than 10m, so we could extend the `go test` timeout to 20m for example and try to improve the length of some of the tests (always using the same set of nats server images so that they are cached for example).

**Comment by pires** [comment]
OK this will maybe suffice for now.

Are we not using the official container images? Also, container images are cached per Kubernetes node alone.

**Pull request merged**
