### PR TITLE
Updates for v1beta1

### PR DESCRIPTION
**Pull request by wallyqs**
Rebased version of PR at https://github.com/nats-io/nats-operator/pull/20/files to include the fixed imports for the repo. Also includes:

- [X] Bump of version of API group and CRD to `nats.io/v1beta1`
- [X] Minikube based Travis build
- [X] README updates and docs
- [X] Updates to script for code generation

### CODE REVIEW

**Comment by pires** [comment]
I think this is a huge PR, very hard to review properly :(

**Comment by wallyqs** [comment]
@pires yeah it is pretty big, can split into smaller chunks and can rebase this one as those changes land

**Comment by pires** [comment]
Looks like a plan, to me.

**Comment by wallyqs** [comment]
Big PR was split, and new one just including the version bump here instead: https://github.com/nats-io/nats-operator/pull/29

**Pull request closed without merging**
